#Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

def fsum(c, a=1, b=2)
	return c < b ? 0 : b.even? ? b + fsum(c, b, a+b) : fsum(c, b, a+b)
end

puts fsum(4E6)