#Pentagonal numbers are generated by the formula, Pn=n(3n?1)/2. The first ten pentagonal numbers are:

#1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

#It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 ? 22 = 48, is not pentagonal.

#Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and D = |Pk ? Pj| is minimised; what is the value of D?

array = Array.new(10000)
tmp = Array.new(10000 * (3*10000-1) / 2 + 1) {|index| false }

1.upto(10000) do |i|
	array[i-1] = i * (3*i-1) / 2
	tmp[array[i-1]] = true
end

find  = false

0.upto(array.length - 3) do |i|
	next if array[i+2] - array[i+1] > array[i]
	(i+1).upto(array.length - 2) do |j|
		next if array[j]+array[i] < array[j+1]
		if tmp[array[j]-array[i]] && tmp[array[j]+array[i]]
			puts array[j]-array[i]
			find = true
			break
		end
	end
	break if find
end

#right
