#Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

#Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
#Pentagonal	 	Pn=n(3n?1)/2	 	1, 5, 12, 22, 35, ...
#Hexagonal	 	Hn=n(2n?1)	 	1, 6, 15, 28, 45, ...
#It can be verified that T285 = P165 = H143 = 40755.

#Find the next triangle number that is also pentagonal and hexagonal.

#ln = 10000
a, b, c = 285, 165, 143
ta, tb, tc = 40755, 40755, 40755

while true
	min = ta < tb ? ta : tb
	min = tc if tc < min
	if min == ta
		a += 1
		ta = a*(a+1)/2
	elsif min == tb
		b += 1 
		tb = b*(3*b-1)/2
	else
		c += 1
		tc = c*(2*c-1)
	end

	break if ta== tb && tb == tc
end
puts ta

#right